# Generated by Django 3.2.4 on 2024-06-03 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Request',
        ),
    ]
